version: '2'

services:
  tomcat-api:
    container_name: tomcat-container-api
    build: ../api.socialanimal.com
    ports:
      - "8081:8080"
      
  tomcat-data:
    container_name: tomcat-container-data
    build: ../data.socialanimal.com
    ports:
      - "8082:8080"