server:
  port: 8081
  tomcat:
    basedir: tomcat/
    accesslog:
      enabled: true
      prefix: access-log
      suffix: .log
      pattern: '%t %a "%r" %s %D'


---

spring:
  profiles: local
  
url:
  data: http://localhost:8082/
---

spring:
 profiles: prod

url:
  data: http://52.1.2.4:8082/