server:
  port: 8081
logging:
  file: app.log
  level.com.socialanimal: DEBUG
---

spring:
  profiles: local
  
url:
  data: http://localhost:8082/
---

spring:
 profiles: prod

url:
  data: http://52.1.2.4:8082/